SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS Advisor;
DROP TABLE IF EXISTS Class;
DROP TABLE IF EXISTS Course;
DROP TABLE IF EXISTS Department;
DROP TABLE IF EXISTS Grade;
DROP TABLE IF EXISTS Instructor;
DROP TABLE IF EXISTS InstructorDepartment;
DROP TABLE IF EXISTS Prerequisite;
DROP TABLE IF EXISTS Program;
DROP TABLE IF EXISTS ResearchFunding;
DROP TABLE IF EXISTS Section;
DROP TABLE IF EXISTS Student;
DROP TABLE IF EXISTS StudentAdvisor;
DROP TABLE IF EXISTS StudentDepartment;
DROP TABLE IF EXISTS StudentProgram;
DROP TABLE IF EXISTS Supervisor;
DROP TABLE IF EXISTS StudentSupervisor;
DROP TABLE IF EXISTS TeachingAssistant;
DROP TABLE IF EXISTS Term;

